name: Production Deployment
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_PRODUCTION_SERVER }}
          username: ${{ secrets.FTP_PRODUCTION_USER }}
          password: ${{ secrets.FTP_PRODUCTION_PW }}
          protocol: ftp
